### ISSUE TITLE
Virtual Environment

### ISSUE THREAD

**Issue by Alfiiya** [mohdshoaib04/pragmatic_lightning_talks#8]
**virtualenv**

 - It is an isolated working copy of python which allows you to work on specific project without worrying that it might affect other projects.

1. It does not actually install separate copies of python,but it does provide an efficient way to keep different project environment isolated.

**INSTALL virtualenv**
2.In order to verify if virtualenv is already installed on your system,you need to run the following command on terminal:
virtualenv --version
3.In case if it is not installed,there are number of ways you can!

- $ sudo apt-get install python-virtualenv

- $ sudo easy_install virtualenv

- $ sudo pip install virtualenv

**SETUP and USE virtualenv**

4.Once virtualenv is installed,you just need to fire up a shell and create your own environment.

- You first need to create a directory for your environment.
       mkdir ~/virtualenvironment

- To create a folder that includes a copy of python:
      virtualenv ~/virtualenvironment/my_folder

- To start with your project,you have to cd into your directory and activate the environment
     cd ~/virtualenvironment/my_folder/bin

- Activate the environment
   source activate

***Use of virtualenv***

virtualenv does not create every file needed to get a whole new python environment.Instead it just uses a link to global environment files instead in order to save disk space and increase speed of virtualenv.

***Pipenv***

- It is a tool that aims to bring all packaging to python world.

- It automatically creates and manages virtualenv for your projects.

- It also adds/removes packages from your PIpfile as you install/uninstall packages.

**Comment by shoaib04** [comment]
Good for a lightning talk !

**Comment by Alfiiya** [comment]
Yes!

**Comment by mohdshoaib04** [comment]
Scheduling today !!
